[project]
name = "fastapi-cb"
version = "0.1.0"
description = "Learning FastAPI from the FastAPI Cookbook"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.11",
]
